sudo: required
services:
- docker
language: python
python:
- '2.7'
script:
- docker build -t recast/wflow-logging:git-"$TRAVIS_BRANCH" .
- docker login -u $DOCKERLOGIN -p $(echo $DOCKERPW|base64 -d)
- docker push recast/wflow-logging:git-"$TRAVIS_BRANCH"
env:
  global:
  - secure: jTOPYdPB31x4XTTo6hV7788oTOUDFmjIVfZREUfv0ErYtcoJP2FEiafn5CpRScZ2aC5cz6i0X+SxFEou7w1mdkKpSppJzexK7+wk8RU3AV647/C4ZGNM+2YEIqsCNSbAOBoGj+Rja5NoY58/w2svBWdjJLiaA9wKWyDIJyor/Cru51RRJ5blc2hU/jGOmWVRqpJEVL2JGCTTtvRyh/BASShE2OHmDISCAaaWIv5Nn6ikBpSmPCuC9xp7kYDQeJB18j0PHwRsHK716aNHfCjBeUpN6ivkrBj4W+S2Ugvu6M7O0qEFkBeROtw9HdcXd02rSi7r0vSTyrNj34cCQTCvHtrYrLInlQ30yIxyDxx/fY4q0IQbPnnQsa3ZwWIXLTQNuo/VhraK2iTMjY6590I+VB2jMY3siv4+Ym/wldjN6caCWBcSZya9KnIRY6fxDOZTK0FnPEkx9oWrkwkvfDLE5sY/ym/xdDP9ImtTW4Bm3yvioY4gSnzRaphKNchXDp9Ju55F5jx33cMVCm0wk6o91LjNI4g2wmibM4rl09r4Jkz2tmzmCQB8Nrx3+McTmXoWWZD8kJgmX682JokxxrAgRRhtcocsT58uFW14fukBrBAsjGLEgH3Yi1JVPBzO8qUKWPNypDk6TQ3Nh8r6ybt5RJvgrObZqsVF7F1i6AlDQMM=
  - secure: h9JzWAev0JKfNFU8FEZLCwtKLj6xC4hA5o3Mg+NHNhBERVJmZvc+Ooqb0eEuObCxRkUgqzLJj/ZfpDSNBSYCOKv8D+k3uTkMnPrpL5CjydsnsNv4q0Bb0IK5Pmq4AHFexLCsATbOpZZdf+hZcnltUpaqgEsc1jlXuiwGS0HdsYqD3+CABi74JmGsRqwFA4Jhf9akHJjRG5BcURYZUM1UXyPAudUD7TdtGVWRFNH8rQ8b49LZNTn38DIu8wlYWFtju+c5UhXUFaNCqPX+aEfVMbsDTf4lRwgaNdjEr3IlgywYM5nLESmBKsTIrBldQmOxYXPRdLD5QKkw1QXy2PQ49X2gyPkduFaS/42ZznNMBFZ1Zyv57CV9j76hcm5xc4R4c2JIkyoojzSOAiJ84Pn3rOBcjjxRGeSjoL3CRsTuzS26vNZMT+H/GdY3UPWldVa0xjdfPdbTBGU6u4mxEMqeBOyks/MyQEEO3zd8L7XmQ8PtSufDdKzXtdbR/k8FNDBuyPcwqQ5cvjLz2FowWDKg9ytyGT31MA82pv9nRlqOqDgmB6QHgeRwdYcbdQNijAR//VRJw27mLmBLD3e8aGDU0bMzQ4u5oluIG1Ek1l7pNLc6+JhEb1KCHVuRnOyA3B73RsQ8n2S8KSq37L9vklMwthIiXw4hZuwMxCvbr9UyNsc=
